name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .deno-version)" >> $GITHUB_ENV
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Run linters
        run:
          deno task check
